shared:
    image: node:8

jobs:
    main:
        requires: [~commit]
        steps:
            - echo: echo "commit"
    staging-commit:
        requires: [~commit:/staging/]
        steps:
            - echo: echo "staging"
    all-commit:
        requires: [~commit:/./]
        # /./ matches any branch name and is used here for illustration only
        # Don't use that regexp in any actual workflow.
        steps:
            - echo: echo all
    staging-pr:
        requires: [~pr:staging]
        steps:
            - echo: echo staging pr
